### ISSUE TITLE
Provide Python bindings for QuantLib with XAD

### ISSUE THREAD

**Issue by auto-differentiation-dev** [auto-differentiation/QuantLib-Risks-Cpp#5]
This should build on the standard QuantLib SWIG, extending it with XAD's tape and its methods as well as the new `Real` type (XAD active type). With this, Python users can calculate sensitivities of their code directly in Python.

The resulting package could then be published in PyPI for easy installation with `pip`.

**Comment by xcelerit-team** [comment]
This has now been published as [QuantLib-Risks](https://pypi.org/project/QuantLib-Risks/) - built from the repository [QuantLib-Risks-Py](https://github.com/auto-differentiation/QuantLib-Risks-Py)
